### ISSUE TITLE
Request on landholding form : "Generate documents" button should be desactivated

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#102]
When opening the form, the "Generate documents" button is activated and should not as long you have not click on the "Print the demand".

![image](https://user-images.githubusercontent.com/6370443/109309342-7110cb00-7843-11eb-8b5c-f96fe4e5b37a.png)

**Comment by offtherailz** [comment]
@MaelREBOUX I tried but can't reproduce, I tried also on your test environment now, but I didn't see the issue. Should I select something in particular to see this bug?
Can you provide a sequence of steps to reproduce this issue ?
![Peek 03-03-2021 16-02.gif](https://images.zenhubusercontent.com/5cd2e72d147fd42f2205c9d1/4c3f8fbd-264c-466b-8734-09ebed729973)

**Comment by MaelREBOUX** [comment]
OK : not present on the last available build https://github.com/georchestra/mapstore2-cadastrapp/suites/2379569218/artifacts/50518522

![image](https://user-images.githubusercontent.com/6370443/117150486-7c8af000-adb8-11eb-9c69-ca9e621dc8e6.png)
