### ISSUE TITLE
Display informations on freshness of the datas on cadastrapp entry pane

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#113]
@MaelREBOUX @catmorales: previously in mfapp, we were showing the 'data year' in the layer name shown in the layer list (if that was enabled in cadastrapp.properties), in mapstore the layer is hidden from the layer list, so an end-user has no way to easily know the data year/date (its only shown on generated pdfs) - @stous thinks it would be nice to display this information somewhere.

we have this info available, as `/cadastrapp/services/getConfiguration` call done at cadastrapp loading has it:
```
dateValiditeMajic | "01/01/2020"
dateValiditeEDIGEO | "01/07/2020"
```

maybe we should display this information on the 'entry pane' of cadastrapp, below *"Sélectionnez l'outil souhaité dans la barre d'outils de gauche pour commencer."* ?

**Comment by sigrmed** [comment]
Yes, I agree with that, it's important information for users.
@MaelREBOUX your opinion ?

**Comment by MaelREBOUX** [comment]
In a general way : we miss infos on the versions of the app or the datas.
So : good idea.

I propose that :

![image](https://user-images.githubusercontent.com/6370443/117148958-0934ae80-adb7-11eb-82ab-de9c6711a74b.png)


Your opinions ?

**Comment by landryb** [comment]
:+1: for me

**Comment by jusabatier** [comment]
Maybe if we have a version for cadastrapp webapp/plugin it can appear also ?

It could help for debugging

**Comment by MaelREBOUX** [comment]
I agree with you @jusabatier  I thinked about that before spleeping yesterday

**Comment by MaelREBOUX** [comment]
Voici my new proposition :

![image](https://user-images.githubusercontent.com/6370443/117429752-a3b3ff80-af27-11eb-84ea-05b46276c74e.png)


The build text show `git rev-parse --short HEAD` and the url is leading to `https://github.com/georchestra/mapstore2-cadastrapp/commit/` + `git rev-parse HEAD`
Is it doable this @offtherailz  ?

Impossible to get the webapp build version because the /cadastrapp/services/getConfiguration? do not expose anything on that.
poke @pierrejego

**Comment by MaelREBOUX** [comment]
I don't know if `git describe --tags` is better or not

**Comment by landryb** [comment]
the git commit is more precise :)

**Comment by tdipisa** [comment]
@MaelREBOUX @catmorales following the above discussion, can you please summarize what is finally required?

**Comment by MaelREBOUX** [comment]
Hello @tdipisa 

We need this :

![image](https://user-images.githubusercontent.com/6370443/120207703-0c438300-c22d-11eb-91b5-ef3d59e00825.png)

"**version du plan cadastral**" is given by the json autoconfiguration `/cadastrapp/services/getConfiguration` + property `dateValiditeEDIGEO`

"**version des données foncières**" is given by the json autoconfiguration `/cadastrapp/services/getConfiguration` + property `dateValiditeMajic`

The **build** text shows `git rev-parse --short HEAD` and the url is leading to `https://github.com/georchestra/mapstore2-cadastrapp/commit/ + git rev-parse HEAD`

**Comment by MaelREBOUX** [comment]
tested and approved

![image](https://user-images.githubusercontent.com/6370443/120814404-217f2100-c54f-11eb-85b9-f42338ee7c62.png)
