### ISSUE TITLE
disable export button when no plot is selected

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#114]
found by @stous when testing, if you do a selection via point/line/polygon, no plot is selected in the result/list, but the 'export' button is enabled, so clicking on it sends a zero-bytes *unknown* file with a mimetype of  `application/x-unknown-content-type`, which is confusing.

You only get a csv file with content once you've selected a plot in the list.

maybe the export button should be disabled/greyed out (like when you open a new empty tab/selection) until a plot is selected.

**Comment by dsuren1** [comment]
Hi @landryb
I'm unable to reproduce the issue in the dev instance of [Cadastrapp](https://georchestra.geo-solutions.it/mapstore/#/context/urbanismecadastrapp). Have attached gif of behavior tested. 
So kindly let me know if I'm missing something. Thanks!
![Plotselection_1](https://user-images.githubusercontent.com/26929983/116858059-6b58ac80-ac1b-11eb-98c4-825c9c425b28.gif)

**Comment by landryb** [comment]
running 1.0.0-rc7, i can reproduce on https://ids.craig.fr/mapstore/#/context/cadastre, unless i'm missing a recent commit... i get it that in the gif you select/deselect all/one plots, but *by default* right after doing a plot selection by point, no plot are checked in the selection result tab, but the export csv button is not greyed out here.

**Comment by dsuren1** [comment]
Hi @landryb
Attached gif, just to clarify the _default_ behavior when plot selection by point
![Plotselection_3](https://user-images.githubusercontent.com/26929983/116866736-90541c00-ac29-11eb-9de2-7876ea1571d7.gif)

Maybe you try can making an extension from the latest code and replace the existing the plugin/extension in the context. Hope that helps

**Comment by landryb** [comment]
i dont see errors in the firefox browser console. what's also strange is that selecting/deselecting entries in the plot selection result *never* greys out the export selection button like i see it does on your capture.

a chrome vs firefox behaviour change ?

**Comment by dsuren1** [comment]
Works fine in firefox as well, for me.
![Plotselection_firefox](https://user-images.githubusercontent.com/26929983/116886824-2fd3d780-ac47-11eb-8f5c-1d495fee08cb.gif)


You can try these,

- Deploy the [latest](https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc8) or redeploy your current version. 
- Or you could try disabling some plugins and have only bare minimum plugins along with Cadastrapp plugin and see if it helps. If you find any plugin affecting Cadastrapp then we can investigate from there. Hope it helps.

**Comment by MaelREBOUX** [comment]
Hello @dsuren1 
Same behaviour here than @landryb  under FireFox and with the last build : https://github.com/georchestra/mapstore2-cadastrapp/suites/2379569218/artifacts/50518522

![ms2_cadastrapp__unknown_txt](https://user-images.githubusercontent.com/6370443/117128559-de8a2c00-ad9d-11eb-954a-b170061aa3b2.gif)

**Comment by tdipisa** [comment]
I'm sorry @landryb and @MaelREBOUX, I'm also not able to reproduce this on our DEV (I'm using FF 85.0.2 (64-bit)) but I can reproduce here: https://ids.craig.fr/mapstore/#/context/cadastre

@MaelREBOUX where have you reproduced that issue? In [portail-test](https://portail-test.sig.rennesmetropole.fr/mapstore/)?

**Comment by tdipisa** [comment]
@MaelREBOUX yes, I've reproduced it in portail test here: https://portail-test.sig.rennesmetropole.fr/mapstore/#/context/master-cadastre

Just to be sure, can you please try to remove some other custom plugin installed like Tabou2?

@landryb do you have some other custom plugin installed in your instance?

I'm just wondering what can be the cause since we are not able to reproduce both locally and in GeoSolutions DEV.

**Comment by tdipisa** [comment]
@landryb @MaelREBOUX please let me know for the above. in your instances I've reproduced also using chrome, so it doesn't seems browser related.

**Comment by landryb** [comment]
cadastrapp is the only 'external' plugin we have in our installation.

**Comment by MaelREBOUX** [comment]
> please try to remove some other custom plugin

In the context "cadastre" or for the whole mapstore2 ?
in the second case : I cannot do that --> @catmorales

But as @landryb said I don't think it is related because the CRAIG has only cadastrapp as plugin.

**Comment by dsuren1** [comment]
I think I found the cause, I believe this happens when accessing user is not authorized or roles of the user is not under allowed ones i.e both isCNIL1 isCNIL2 is false.

Reason, it works fine for us is because we have roles which are allowed to perform certain additional features in the plugin (in other words authenticated user) 
I will create a fix soon.

**Comment by MaelREBOUX** [comment]
I confirm @dsuren1  !

left : user with non CNIL right  |  right : my account with CNIL2

![image](https://user-images.githubusercontent.com/6370443/117143915-a1c83000-adb1-11eb-9aac-4464a7550811.png)

**Comment by tdipisa** [comment]
Thank you so much @dsuren1

**Comment by MaelREBOUX** [comment]
nice. waiting for waiting for https://github.com/georchestra/mapstore2-cadastrapp/actions/runs/813743353 to test

**Comment by MaelREBOUX** [comment]
![image](https://user-images.githubusercontent.com/6370443/117160000-0ccd3300-adc1-11eb-9966-cb8eb06ac3e8.png)

solved !

**Comment by MaelREBOUX** [comment]
oups : I let @landryb close after confirmation on its infra

**Comment by landryb** [comment]
tested by deploying `1.0.0-rc9` on our testing/dev infra, problem fixed - thanks @dsuren1 !
