### ISSUE TITLE
Information form : string harcoded ?

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#116]
When asking a municipality which is not know : 

![image](https://user-images.githubusercontent.com/6370443/117147463-94ad4000-adb5-11eb-8642-a0a0397c2083.png)

Cannot find this string in the localization strings. Wrong am I or this string is hardcoded in english ?

**Comment by offtherailz** [comment]
This is a default string of the search tool of the library used, so it is inside the library.
I created this PR to localize also that messages.

**Comment by MaelREBOUX** [comment]
I confirm : it is better now

![image](https://user-images.githubusercontent.com/6370443/117635751-6c8c5b00-b180-11eb-9e57-e4ee42166848.png)
