### ISSUE TITLE
Plots Selection

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#12]
The **Plots selection** panel allows the users to browse search results of cadastrapp parcels regardless of the search type used (by Point, Line, Polygon or by Plot, Owner, Co-Owner etc.). Below a sample of old UI

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/2557d4c4-2715-409a-94f1-a609aaef2931)

The corresponding UI for the MS plugin is reported below (according to the mockup [here](http://demo.geo-solutions.it/mockups/mapstore2/cadastrapp/#/config)).

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/0a41d297-57e5-42b8-8476-eafedb32ab58)

All search results are reported here (as described in issues #9, #10 and #11 for example) in a table inside a search Tab. There are also two action toolbars:

- One to simply manage search Tab: remove the active one by also removing al contents

![image](https://user-images.githubusercontent.com/1280027/95213308-f80acb80-07ee-11eb-9fd2-089a97b43857.png)

- One that allows the user to perform some actions on result records

![image](https://user-images.githubusercontent.com/1280027/95213338-ffca7000-07ee-11eb-9125-b6ef9ad49304.png)

Below the list of features:

- It is possible for the user to create new Tabs to host search results. According to the search type choosen by the user, the behavior is a bit different. An example is the one described in issues #9, #10 and #11, other kind of search type automatically open a new dedicated results Tab instead (it is anyway described in the related issue).
- Each record in table can be selected 
- By default, in the action toolbar only the zoom button is enabled: if no records are selected in the table it allows to zoom the map to the extent related to the entire list of results. Otherwise, is some record is selected, the zoom is performed only to the selected ones.
- As soon as one or more records are selected, other buttons in the toolbar are enabled accordingly:
   - **Delete Entry** (to be added, currently missing in the mockup): remove the selected entries from the table (only client side)
   - **Landry property**: perform a specific request to the mapfishapp web service (to replicate) using selection parameters to open the result in a new browser tab
   - **Export selection**: perform a specific request to the cadastrapp web service (to replicate) using selection parameters to export selection data by type (some of the export type are available according to the user role, see the functionality matrix [here ](http://docs.georchestra.org/cadastrapp/guide_developpeur/index.html#) and compare it with the mapfishapp using also an user with different roles)
   - **Information form**: this button opens the **Information Form** modal using selection parameters (the implementation of this modal is part of the issue #13)

**Comment by landryb** [comment]
fwiw, **landry property** doesnt make any sense as a string/name, i think that was a leftover from @pierrejego developments - iirc that's for the notion of 'unite fonciere' which could be translated as 'owned unit' i think. @MaelREBOUX ?

can we stop using this nonsense string ? thanks ;)

(also, great work on summarizing all those behaviours in detail. That's **much** welcomed!)

**Comment by tdipisa** [comment]
> fwiw, **landry property** doesnt make any sense as a string/name, i think that was a leftover from @pierrejego developments - iirc that's for the notion of 'unite fonciere' which could be translated as 'owned unit' i think. @MaelREBOUX ?
> 
> can we stop using this nonsense string ? thanks ;)
> 
> (also, great work on summarizing all those behaviours in detail. That's **much** welcomed!)

@landryb, as far as I can see it provides the same functionality of "Unite Fonciere", therefore the name should be this one in my opinion.

**Comment by landryb** [comment]
sure that's 100% fine, but as you were using english names i was wondering for what it should be changed here and there :)
