### ISSUE TITLE
Improve some strings

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#121]
While making / reading the next version of the documentation, some strings to change.

Note for myself.

- [x] N° de plan -> Numéro. (because it is rootly "N° au plan / N° sur le plan")

https://github.com/georchestra/mapstore2-cadastrapp/blob/ae71948e206c188fbde35417e495f103c76f58e1/assets/translations/data.fr-FR.json#L22

https://github.com/georchestra/mapstore2-cadastrapp/blob/ae71948e206c188fbde35417e495f103c76f58e1/assets/translations/data.fr-FR.json#L22

- [x] Outils Cadastre -> Cadastrapp (apparaît tout en haut = pub)

https://github.com/georchestra/mapstore2-cadastrapp/blob/0c6c66709e7ce401cd2c49d9f461fc6bd50d4ce5/assets/translations/data.fr-FR.json#L80

- [x] uniteFonciere -> pb sur le tooltip. devrait être : "Cliquer sur une parcelle pour afficher l'unité foncière"

https://github.com/georchestra/mapstore2-cadastrapp/blob/17b473739e258e00734e6d10bd04688cabcf85aa/assets/translations/data.fr-FR.json#L316

**Comment by MaelREBOUX** [comment]
hello @offtherailz 

The `patch_fr_translation` branch is said "protected" and I cannot use it. It seems not maintened.
May I use it (after git rebas of course ?)

**Comment by landryb** [comment]
it's usually bad practice to reuse branches that were previously used in pull requests, that might mess up the previous PR ? branches are cheap..

**Comment by offtherailz** [comment]
I suggest to create a new branch from the updated master, so you have all the latest changes and you don't have to solve conflicts or similar, applying only your changes.
We use to do it and is simpler.

**Comment by MaelREBOUX** [comment]
`create a new branch` ok. I'll do it.

**Comment by tdipisa** [comment]
@MaelREBOUX do you have any news for this?

**Comment by MaelREBOUX** [comment]
I'm on
