### ISSUE TITLE
default doc url now points to inexistant page

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#122]
https://github.com/georchestra/mapstore2-cadastrapp/blob/ae71948e206c188fbde35417e495f103c76f58e1/assets/index.json#L9 points https://github.com/georchestra/cadastrapp/wiki/Guide-Utilisateur which was removed and was about the mfapp version of the doc, now it should be https://docs.georchestra.org/cadastrapp/latest/guide_utilisateur/ per georchestra/cadastrapp#564

**Comment by MaelREBOUX** [comment]
fix by https://github.com/georchestra/mapstore2-cadastrapp/commit/8d80d703ee20a455c149b5f6a0ef96ad7e7aaad8

**Comment by landryb** [comment]
there are still occurences of the previous url:
```
/data/src/georchestra/mapstore2-cadastrapp $git grep wiki
README.md:    "helpUrl": "https://github.com/georchestra/cadastrapp/wiki/Guide-Utilisateur",
assets/index.json:        "helpUrl": "https://github.com/georchestra/cadastrapp/wiki/Guide-Utilisateur",
js/extension/constants.js:export const DEFAULT_HELP_URL = 'https://github.com/georchestra/cadastrapp/wiki/Guide-Utilisateur';
localConfig.json:            "helpUrl": "https://github.com/georchestra/cadastrapp/wiki/Guide-Utilisateur",

```

**Comment by landryb** [comment]
sorry, wasnt on master when i checked, but there was still one occurence in `js/extension/constants.js`
