### ISSUE TITLE
Bug in owner search (2 account looked for while only 1 is allowed)

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#123]
@tdipisa we think we have found a bug that have passed our tests.

Here the steps to reproduce on our test portal :

1. open cadastrapp
2. clic sur owner search
3.  search "chauvin frederic"

Here we have the choice to select a suggestion in the list OR to echap the suggestion to show a special window which lists the owners.

The behaviour of the search by the special window is OK. 
Choosing "M CHAUVIN FREDERIC" -> 3 parcels
Choosing "M CHAUVIN THOMAS FREDERIC MICHEL" -> 1 parcel

But then : the UI let us choose "M CHAUVIN FREDERIC" directly and if we valid the search we are getting 4 parcels.
So the user believes that this ower has 4 parcels while he owns only 3.

In mapfishapp it cannot happened : if more than 1 owner account is foud we systemacally open the special owner list window and we are obliged to choose one account.

We noted that the mapstore plugin is building a query to `/cadastrapp/services/getParcelle` with 2 owner account while the user choose only one row in the dropdown list. So here is the origin of 4 parcels while 3 is awaited.

![image](https://user-images.githubusercontent.com/6370443/120210758-70b41180-c230-11eb-95e8-2f7134847a55.png)

Here the current behaviour in mapfishapp

![ms2_cadastrapp_bogue_chauvin_mapfishapp](https://user-images.githubusercontent.com/6370443/120210802-7e699700-c230-11eb-80c1-9f7ebd3ad0fa.gif)

And the problem in mapstore

![ms2_cadastrapp_bogue_chauvin_mapstore](https://user-images.githubusercontent.com/6370443/120210817-81fd1e00-c230-11eb-820a-6336a907a7af.gif)

**Comment by offtherailz** [comment]
Ok, I never find out this use case. I hoped that that step could be skipped if I select a user, but I see that there is still ambiguity.
So I created a PR that should solve this issue. Now, even if I select an existing record, if the search returns more than one owner, it will ask for owner selection.

**Comment by tdipisa** [comment]
@catmorales, it should be fixed, let us know if we can close the issue.

**Comment by catmorales** [comment]
I deployed the tag 1.0.0-rc12 this morning in production. it seems not fixed on this tag. 
I dont't have time to test it now .

**Comment by tdipisa** [comment]
@offtherailz, any feedback?

**Comment by offtherailz** [comment]
#123 is fixed by rc13 . Please try the rc13.
See this: 
https://github.com/georchestra/mapstore2-cadastrapp/releases
![image](https://user-images.githubusercontent.com/1279510/121038078-445c4000-c7b0-11eb-8cab-b02c0353703a.png)

**Comment by catmorales** [comment]
Ok i'll try later. thank you @offtherailz

**Comment by MaelREBOUX** [comment]
Hello. Sorry to be late.
Away on monday and now I'm busy by the geOcom since tuesday. I test tomorrow friday. Sure.

**Comment by MaelREBOUX** [comment]
Hello.

**OK : the bogue is fixed.** It is sure. Congrats.

But now we have a bizarre UX that we must correct.

I you search with the "escape button method" -> it opens the owner list window. ok no pb.
Then you choose one owner but the dropdown list is anyway filled with all the owners. Where **we expect only the choosed owner from the owner "special window".**

I hope I'm clear ?

![ms2_cadastrapp_bogue_chauvin_mapstore_2](https://user-images.githubusercontent.com/6370443/121654665-40753a00-ca9e-11eb-9791-185a3699dd9f.gif)

**Comment by tdipisa** [comment]
@MaelREBOUX can you please open a new issue for the problem you described above?

**Comment by MaelREBOUX** [comment]
ok. I thinked about it.

**Comment by MaelREBOUX** [comment]
=> #130
