### ISSUE TITLE
result selection table : the order of the columns is not adequate

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#128]
Hello. Sorry I don't know how we all have missed this before : the order of the columns is not adequate.

![image](https://user-images.githubusercontent.com/6370443/120826204-770cfb00-c55a-11eb-9232-05fdb4eaadd4.png)

The traditional order is :
- commune / municipality
- section
- numero
- adresse
- contenance

Please change to this order. I checked : it is the order in the mapsfishapp addon.

**Comment by offtherailz** [comment]
Fixed by @dsuren1 , please try this:
https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc15

**Comment by MaelREBOUX** [comment]
Good with 1.0.0-rc15 !

![image](https://user-images.githubusercontent.com/6370443/125288914-f0002f00-e31e-11eb-807a-47ff91d402a2.png)
