### ISSUE TITLE
Information Form

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#13]
The **Information Form** is one of the most important component because it allows to retrieve detailed information on the selected cadastral parcel. There are also further functionalities connected to it to mainly export selected data in CSV  and PDF formats by interacting with the backend services.

The **Information Form** reports all information of one or multiple selected cadastral parcels in **Plots selection** to browse connected data for: **Plot**, **Owners**, **Co-Owners**, **Buildings**, **Tax subdivisions** and a possible **Mutation history** 
All information are reported in a tabular view according to the user roles as explained in the Epic #1.

![image](https://user-images.githubusercontent.com/1280027/95483455-874ee500-098f-11eb-9d00-573e93460e32.png)

To display detailed information through the **Information Form** an accordion layout must be used in a modal window that opens as soon the user click on the related button in the **Plots Selection** toolbar (as reported in the [mockup](http://demo.geo-solutions.it/mockups/mapstore2/cadastrapp/#/config), we can evaluate a better styling of accordion panels during developments):

![cadastrap_infoform](https://user-images.githubusercontent.com/1280027/95484223-7c488480-0990-11eb-8c94-8594ca56a371.gif)

Tables in each accordion panel are populated by retrieving records from the cadastrapp backend services (requests performed by the [old client](https://georchestra.geo-solutions.it/mapfishapp/) can be checked by looking at the browser developer tool and these are described in the online documentation [here](http://docs.georchestra.org/cadastrapp/guide_developpeur/index.html#fiche-information-parcelle) along with the associated user roles).

![cadastrap_infoform2](https://user-images.githubusercontent.com/1280027/95485396-f2012000-0991-11eb-8b4a-718585964b4e.gif)

Tables in each accordion panel are organized in different Tabs, one for each information category: **Plot**, **Owners**, **Co-Owners**, **Buildings**, **Tax subdivisions** and a possible **Mutation history**. Tabs to be displayed are related to the user role (see #1).

![image](https://user-images.githubusercontent.com/1280027/95485383-ea417b80-0991-11eb-815b-3ffcf61bdabe.png)

### Actions associated to each table Tab

There are different actions available depending on the Tab. All actions require interactions with the cadastrapp webservices to retrieve related information.

### Plot

- **Plot Information**: it provides an extract of the computerized cadastral plan in PDF format (a request must be performed to the cadastrapp webservice for this by sending the involved client side parameters)

![image](https://user-images.githubusercontent.com/1280027/95486220-07c31500-0993-11eb-9e63-192406ae843a.png)

- The user can choose if also owner information must be included in the final PDF or not
- The user can also choose the base map to be used for the final print.

### Owners

- **Property List**: allows to retrieve the Property statement in PDF format or CSV accoridng to the user selection

![image](https://user-images.githubusercontent.com/1280027/95486738-b0717480-0993-11eb-9bde-78ad3cde327f.png)

- The user can choose if all properties must be included in the final export instead of only the current plot
- The user can also choose the format of the export: PDF or CSV

### Co-Owners

Mostly the same of Owners but for Co-Owners properties

### Building(s)

- **Buildings**: list of of available buildings lists, the list of buildings in table changes according to that selection if available

Button corresponding to the actions below are present in the left hand toolbar and they are enabled only if one or more records is selected in table:

- **Property List**: allows to retrieve the Property statement in PDF format or CSV accoridng to the user selection
![image](https://user-images.githubusercontent.com/1280027/95488613-0cd59380-0996-11eb-8d04-367ca0ccde80.png)

- **Description**: open a popup containing a description of the building (**it is possible also doing a double click on a record to open the popup**)

- **Boundle**: allows to export the Co-ownership lots in PDF or CSV format
![image](https://user-images.githubusercontent.com/1280027/95488541-f7f90000-0995-11eb-9448-8bd3f7178a9c.png)

### Other useful information
Since this tool allows multiple user interactions, it is possible to convert this issue in Epic and split it in sub-issues.

**Comment by offtherailz** [comment]
About the thubmnail of the list
![image](https://user-images.githubusercontent.com/1279510/105501259-453e7a80-5cc4-11eb-8aac-696291cb4327.png)
There are some references to `https://public.sig.rennesmetropole.fr/ressources/app/georchestra/cadastrapp/images/cadastre.png` coming from [`getConfuration`](https://georchestra.geo-solutions.it/cadastrapp/services/getConfiguration).
Can I assume these are installed together with the back-end ?

**Comment by tdipisa** [comment]
@offtherailz it should be as far as I know, @catmorales @MaelREBOUX can you confirm the above question?

**Comment by landryb** [comment]
afaict they should be configured in `cadastrapp.properties`, cf `pdf.baseMap.0.title.thumbnail` in https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/src/main/resources/cadastrapp.properties#L59
