### ISSUE TITLE
Owner's 'Nom de naissance' are truncated

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-cadastrapp#131]
In the Plot's info table (batiment for example), the owner's 'Nom de naissance' are truncated.

There is the same problem in the exported 'Relevé de propriété'.

**Comment by offtherailz** [comment]
You mean this? 
![image](https://user-images.githubusercontent.com/1279510/122923468-0b51cd00-d365-11eb-8cab-cf1165079b00.png)

If the column is too small for the value, you can resize them. 
![Peek 22-06-2021 14-20](https://user-images.githubusercontent.com/1279510/122923392-f6753980-d364-11eb-9b3f-af4b3ce21520.gif)

**Comment by jusabatier** [comment]
No, I mean that when the 'Nom de naissance' is too long it's truncated even if I resize the column.

I have tested throught 2 examples : one time with a name trucated at 23 chars and the second at 29 chars.
The names are also truncated on the generated RP.

To compare with mapfishapp plugin, I tested the same owners and they are not trucated.

**Comment by offtherailz** [comment]
I can not replicate, so I think they are truncated on server side (by server, or db).

 I've a string of 49 chars in birth date not trucated.

![122936736-ac468500-d371-11eb-8edc-389503179f1b](https://user-images.githubusercontent.com/1279510/122938928-74404180-d373-11eb-8442-ca53ae56044b.jpg)

**Comment by offtherailz** [comment]
Can you please check if you receive the string from the service already truncated?

**Comment by jusabatier** [comment]
I tested it and effectively it seems to be a problem with the server data.

Sorry for inconvenience

**Comment by offtherailz** [comment]
No problem, good to know ;)
