### ISSUE TITLE
positionning conflict between cadastrapp pane and omnibar/burger menu

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#133]
This is a followup to #73 which only fixed **one** conflict between cadastrapp pane and identify tool popup.

Users of cadastrapp are (once the cadastrapp pane is open) being confused by not being able to enter an address in the omnibar, or they complain they cant print the map or access the annotation tool pane or being able to add more layers via layer catalog... (eg all the tools available in the burger menu).

Sure, one can always close cadastrapp pane to reaccess all those features, but then one manually needs to readd the cadastre layer to be able to draw on it or print an area of interest.

Sure, i'll try to add the cadastre layer to the default map shipped in the context, but then i guess it might/will conflict with the same layer being loaded by cadastrapp when opening the pane.

So, all in all, i'd like to have a discussion on how to avoid all those positioning conflicts of tools hiding each other and making other tools unaccessible.. cant the burger menu and the omnibar position be relative to the cadastrapp pane, like this is the case for the other tools available in the bottom right toolbar ?

@jusabatier @MaelREBOUX @catmorales ?

**Comment by landryb** [comment]
i've tested adding the cadastre layer to the map context (from the same source returned by `/cadastrapp/services/getConfiguration`), and opening the cadastrapp pane doesn't readd it a second time (and closing the pane doesnt remove the layer either), so that can be a workaround, but users will still have to open/close the pane to access the omnibar and the burger menu to reach annotate/add layer/print. A bit awkward...

**Comment by MaelREBOUX** [comment]
@landryb  do you except this ?
With / without the burger menu (to discuss...) ?

![capture_346-2](https://user-images.githubusercontent.com/6370443/125296070-32793a00-e326-11eb-9e9b-787344c2807a.png)

**Comment by landryb** [comment]
that would seem logical, *with* the regular burger menu that users will try accessing for other tools (measure, annotation,etc..) - yes i know they can close the cadastrapp pane, but they'll be confused anyway.

**Comment by Gaetanbrl** [comment]
> that would seem logical, with the regular burger menu that users will try accessing for other tools (measure, annotation,etc..) - yes i know they can close the cadastrapp pane, but they'll be confused anyway.

Many tools can't be open in the same time to avoid conflict between MapStore2 core action.

E.g if you open Cadastrapp and Annotation, what will happend with the main toolbar display or with others map clic actions ?
For this example, Annotation needs to close Cadastrapp (not sur but seems logical and it's maybe the current behavior).

So, it could be a good idea to keep visible the "other tools" burger buttons **only if all plugins inside could close visible plugin**.

About text bar, this tool have no conflict with cadastrapp (i think), so it should be useable all the time.

**Comment by Gaetanbrl** [comment]
In addition, some widgets could be hidden by a plugin UI.

**Comment by catmorales** [comment]
We will have the same problem with urbanism plugin because a lot of users needs to have both plugins (cadastrapp and urbanism) opened at the same time .

**Comment by landryb** [comment]
Fixed by #156 / duplicate of #150, at least for being able to access printing/omnibar when using cadastrapp. Yay!

**Comment by MaelREBOUX** [comment]
May we close this issue now ?

**Comment by landryb** [comment]
Yay !
