### ISSUE TITLE
Lost the identify tool while Cadastrapp plugin is loaded

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#134]
Hello.

I don't know if it is related to #73 but with https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc15

I cannot use the identify tool. See below :

- I load a context dedicated to urba foncier with the cadastrapp plugin in it
- clic somewhere on the map -> nothing
- activate cadastrapp -> activate the tool "select by point"
- clic somewhere on the map -> get a result selection in cadastrapp (ok)
- unactivate the tool "select by point" (so I should be in the "standard mode" ie getFeatureInfo on click)
- clic somewhere on the map -> nothing

The apparition of the cadastrapp Tooltip is normal (2 s latence over the map).

![ms2_bug_cadastrap_identify_tool](https://user-images.githubusercontent.com/6370443/125291496-c399e200-e321-11eb-81e8-b6a8b63e3c6a.gif)

**Comment by offtherailz** [comment]
I was able to replicate only removing Identify plugin from `localConfig.json`, not able to replicate in a context.
The marker seems to be an issue of the feature info tool. See this: 
https://github.com/geosolutions-it/MapStore2/issues/7111

Anyway, I can remove the marker when cadastrapp is active by calling an additional function that clean up feature info. 
I did this in PR #136 

The result will be that you will see the marker, but it will disappear as well as you open cadastrapp. Is it ok for you?

**Comment by offtherailz** [comment]
Please try https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc16 to check if this fix your issue

**Comment by MaelREBOUX** [comment]
Hello @offtherailz 

So. We realized this morning that we did not have the same behaviour between our test and prod portal. And... on the test portal the identifiy tool was missing in the context ! Don't know why it was but it was...
So my screencast made on test showed something totally normal.

*The behaviour in the rc15 version is completely suitable for us. The behaviour of the rc16 is not suitable and you could revert the commits and delete the rc16 release.*

Arguments : we can't let the identify tool result panel hidden for the users.  They clic on the map and nothing (visible) happens. Not suitable at all.

I totally apologize for the time wasted...


For memory : RC15 then RC16

![ms2_cadasrapp_rc15_identify](https://user-images.githubusercontent.com/6370443/126168051-a6a09268-3513-446d-a89a-e0eecb8d138c.gif)

---

![ms2_cadasrapp_rc16_identify](https://user-images.githubusercontent.com/6370443/126168070-762daf0f-895a-4e76-9023-00b226d43fdf.gif)

**Comment by tdipisa** [comment]
I'm sorry @MaelREBOUX but what you wrote above is quite strange, I think. 

> And... on the test portal the identifiy tool was missing in the context ! Don't know why it was but it was...

Yes, the Identify tool was missing in the context but, indeed, we only provided a small fix for that specific use case when the Identify plugin is not present in the context: nothing related to what you are showing above. The behavior you have now in prod portal with rc15 (I tested it [here](https://portail.sig.rennesmetropole.fr/mapstore/#/context/master-urba-foncier)) is exactly the same we have in our DEV using rc16 below a GIF from our DEV:

![cadastrapp_1](https://user-images.githubusercontent.com/1280027/126305909-3005fa76-7aa1-449f-901f-2373873aa459.gif)

Therefore I can only suppose there is something broken somewhere else in your test instance: maybe are there some other extension that wrongly interacts with this?

**Comment by MaelREBOUX** [comment]
okayy : I have a completely different behaviour while making the same actions as you on our test portal.

After deactivate the "select by point" tool then clic on the map I get this :

![image](https://user-images.githubusercontent.com/6370443/126322229-b5c9d4b7-82a8-4403-8bf2-8659d841738b.png)

> I can only suppose there is something broken somewhere else in your test instance: maybe are there some other extension that wrongly interacts with this?

I can't know... But it seems so. I make investigation....

**Comment by MaelREBOUX** [comment]
Well, I did something I dislike : I deploy the RC16 in production.
And bim : I have I get the same behaviour as you. 
So we have bad interactions on test. But these plugins are not loaded in my test context. It is veray disappointing.

So : what I see is what I expected : no possibility to use the GetFeatureInfo tool while cadastrapp is loaded.

Thank you @tdipisa and @offtherailz

**Comment by tdipisa** [comment]
@MaelREBOUX just to answer to this:

>So we have bad interactions on test. But these plugins are not loaded in my test context. It is veray disappointing.

As previously reported by @offtherailz in the past, if the problem is due to other custom plugins, the problem can occur in a context even if these plugins have not been enabled in it (e.g. epics act globally regardless of whether their plugins are present or not so it should be up to the related plugin to make the appropriate checks to avoid unwanted effects when the plugin itself is disabled or closed).

**Comment by tdipisa** [comment]
@MaelREBOUX 

I've anyway asked @offtherailz to open [this issue](https://github.com/geosolutions-it/MapStore2/issues/7127) to keep track of these things and try to schedule an investigation for a possible enhancement in the future.

**Comment by MaelREBOUX** [comment]
Thank you for the issue.
more isolated / not loaded => sure it will improve MapStore.

For the plugins. They were removed then I saw yesterday that they ave been restored.
Sorry for the noise.
