### ISSUE TITLE
Bordereau parcellaire : miss the "Export in batch" functionnality

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#135]
Well, it seems that we totally missed a famous functionnality.
The one which let a user to export in a single PDF file all the Bordereaux parcellaires from a plot selection.

![ms2_bug_cadastrap_batch_bp](https://user-images.githubusercontent.com/6370443/125293417-aebe4e00-e323-11eb-8f8c-f4632cbf1fc9.gif)

From my point of view, with the new UI in mapstore, we should have an item "Export BP in batch" in this menu :

![image](https://user-images.githubusercontent.com/6370443/125293812-0f4d8b00-e324-11eb-9455-ec751ab85fbc.png)

What do you think @pierrejego @landryb @jusabatier @LouiseBAILLET ?

**Comment by dsuren1** [comment]
**Tasks**
- Add new button under Plot selection export dropdown toolbar to export all plot selections as PDF
- Add similar field to the new dialog 
- Guest user cannot see _Owner information_ fields and can only select _baseMap_ and export as pdf
- User with roles can choose between _with_ and _without_ owner information to be added in the exported pdf

**Comment by offtherailz** [comment]
New version with this fix available here: 
https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc17

**Comment by catmorales** [comment]
I have deployed the rc17 yet in portail-test and it seems OK:
![image](https://user-images.githubusercontent.com/4659829/128505469-eb953ad9-7f36-4332-b0e0-6a3db0f6edeb.png)
![image](https://user-images.githubusercontent.com/4659829/128505622-fa29fcef-cbc3-4078-8c9d-586c6b421b5a.png)

@jusabatier  could you test too ?

**Comment by catmorales** [comment]
I will deploy it on production.
Thanks @offtherailz  and @tdipisa  for your reactivity

**Comment by catmorales** [comment]
With a big selection i have a 504 Gateway Timeout.

**Comment by offtherailz** [comment]
Usually 504 Gateway Timeout are problems coming from the server. 
It is taking too much to respond. So I think with big selection you may have the same problem on the original cadastrapp, if the request is exactly the same

**Comment by tdipisa** [comment]
> Usually 504 Gateway Timeout are problems coming from the server.
> It is taking too much to respond. So I think with big selection you may have the same problem on the original cadastrapp, if the request is exactly the same

That's the case, yes

**Comment by catmorales** [comment]
Yes i think so, il will check.

**Comment by jusabatier** [comment]
I tested it here also and it works well

**Comment by tdipisa** [comment]
@catmorales can we close this?

**Comment by catmorales** [comment]
yes you can ;)

**Comment by MaelREBOUX** [comment]
Humm... still 504 error here with only 10 plot selected. Our cadastrapp service hangs up after 50 s.

So I cannot check this feature right now but I trust @jusabatier  :)
