### ISSUE TITLE
Unite Fonciere

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#14]
This functionality is the same reported in issue #12 (Landry property, we should agree on a better name to use for both, see comment).

![image](https://user-images.githubusercontent.com/1280027/95215837-bb8c9f00-07f1-11eb-92f1-416e1dd576f1.png)

As soon as the user activates this tool (toggle button) in the cadastrapp action toolbar, it is possible to select a cadastral parcel with a single click on map (**the parcel is highlighted on map**). As reported in issue #12, the functionality here is the same:

>Landry property: perform a specific request to the mapfishapp web service (to replicate) using selection parameters to open the result in a new browser tab

![image](https://user-images.githubusercontent.com/1280027/95216332-39e94100-07f2-11eb-93bb-2f853962e4b9.png)

Below is the related action button MS side (**the icon provided in the mockup is temporary, we should fine a better one**)

![image](https://user-images.githubusercontent.com/1280027/95216178-0f978380-07f2-11eb-956a-558d6eb530a8.png)

The backend requests to perform for this tool can be checked by testing the [DEV instance](https://georchestra.geo-solutions.it/mapfishapp/) and taking into account the functionalities matrix [here](http://docs.georchestra.org/cadastrapp/guide_developpeur/index.html#) if needed.

**Comment by offtherailz** [comment]
@landryb During the development I noticed that reusing `ficheUniteFonciere.html` is not so convenient. 

**Summary of the current system:** 

The current html page for this functionality is deployed in `mapfish` app, includes Openlayers 2.11 and assumes that the opener window (that now is the geIrchestra viewer and will be MapStore in the new implementation) uses the same lib version ( to clone layers ). Moreover the opener should store some variables in some global variables (window scope) to do the proper requests.

** New implementation**
MapStore uses OpenLayers 3 and so the layer cloning functionality (and also global variables) should be anyway reviewed and adjusted. And reusing this page means also to keep it installed in mapfish app with all JS libs and so on...

To avoid it, we suggest to re-implement this functionality inside MapStore, without opening this HTML anymore. 
A solution like this could get many advantages:
 - The installation is easy. Only the zip (and the back-end) nothing more
 - The user may not need to leave the current page. The page could be rendered in a modal (resizable/closable) on top of the map. So it improves usability.

**Comment by landryb** [comment]
@MaelREBOUX @pierrejego you were the ones doing the printing via `ficheUniteFonciere.html`, any ideas ? I personally dont specially care about that and always found it weird to have different ways of printing a result. And opening a popup in 2021 gives me *shivers*.

**Comment by pierrejego** [comment]
Hi,
for this point, we wanted to print without using server side ( no mapfishprint). 

The more simple it is for user, the best it is for me 👍  your solution looks good for me.

@offtherailz I did not understood what will be in " the zip ", this will be an additional extension ?

**Comment by tdipisa** [comment]
@pierrejego we will proceed then on embedding this in the MS plugin, we will check for the print before.

**Comment by offtherailz** [comment]
@pierrejego the zip extension should ideally everything concerning the extension (cadastrapp), and it is actually installed in "/mapstore" path. In the comment I only expressed my concerns about keeping that file (`ficheUniteFonciere.html`) in "/mapfish", that may require an additional step for those how want install cadastrapp client part. 

But with this solution, cadastrapp extension will be the only thing to install (for client part).

**Comment by MaelREBOUX** [comment]
> opening a popup in 2021 gives me shivers.

+100

@tdipisa has just exposed a proposition to us that consists in "doing" all the job inside MapStore.
By this way users wil stay inside MS and it is the best way. Sure.
