### ISSUE TITLE
Missing the type of the way in the result selection tab

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#146]
As one can see below : we miss the type of the way in the string :

![image](https://user-images.githubusercontent.com/6370443/148417416-f2503c9f-4f0f-4810-b9b3-734fffb529d7.png)

"5 DU PRESSOIR"  should be "5 RUE DU PRESSOIR"

It should use the `cconvo` attribute which is in the JSON data returned by the getParcelle API call.

**Comment by MaelREBOUX** [comment]
well the source is here : https://github.com/georchestra/mapstore2-cadastrapp/blob/e9c934257b88b7c075b0e416b230fe9d14815a18/js/extension/components/table/PlotsSelectionTable.jsx#L49

**Comment by MaelREBOUX** [comment]
what do you think @offtherailz  ?

**Comment by tdipisa** [comment]
@MaelREBOUX we will check it as soon as possible.

**Comment by offtherailz** [comment]
waiting for other PRs to be merged in order to build a rc and test.
