### ISSUE TITLE
Problem with EPSG:2154 and "Unite Fonciere"

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-cadastrapp#157]
Our MS instance is configured with EPSG:2154 and we noticed that when requesting informations about "Unité foncière", the map isn't displayed : 

![image](https://user-images.githubusercontent.com/8310116/167808105-bb91d86a-1eea-4f31-b5f8-20f2a8475315.png)

Is there a special configuration to handle that ?
The other PDF's map generations work well.

**Comment by landryb** [comment]
@jusabatier is it still an issue or you've find a way to work around it ?

**Comment by jusabatier** [comment]
Finally, we configured our MS with EPSG:3857
