### ISSUE TITLE
selection layer below parcel layer at first extension load

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#169]
with v2.0.0-rc, i have a weird behaviour where the selection layer is **below** the plot layer, making it invisible if the selected plot is a building that covers the complete plot.

see animated gif below:
![cadastrapp](https://user-images.githubusercontent.com/3421760/183896241-5a48bce4-b015-452b-b798-2ca89833b01d.gif)

closing/reopening the cadastrapp pane makes the selection layer go **above** the plot layer as expected.

i've tested it with a context configured with the plot layer (where i've witnessed #166, the plot layer is loaded twice in the map) or with cadastrapp being loaded in the default config (the gif was made in this config)

@catmorales ?

**Comment by landryb** [comment]
can't reproduce the issue with [1.0.0-rc15](https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc15) so probably a regression.

**Comment by tdipisa** [comment]
@landryb I will ask the team for a check. Thank you.

**Comment by tdipisa** [comment]
@landryb we fixed this through #177. Please, see PR description if you need details. fell free to close this issue if the fix works for you.

**Comment by landryb** [comment]
> @landryb we fixed this through #177. Please, see PR description if you need details. Feel free to close this issue if the fix works for you.

thanks @alexander-fedorenko, i've tested #177 and can confirm that the selection layer is now correctly above parcel layer at first extension load.

@tdipisa if you can also merge/review #171 & #176 before cutting another rc that would be nice - thanks ! :)

**Comment by tdipisa** [comment]
Thank you @landryb. I've assigned @dsuren1 as a reviewer for these,
