### ISSUE TITLE
UF broken with latest 2023.02.00-RC1-geOrchestra

### ISSUE THREAD

**Issue by jusabatier** [georchestra/mapstore2-cadastrapp#182]
Since we deploy the latest 2023.02.00-RC1-geOrchestra, when trying to interrogate a land unit (Unité Foncière), it result in an error message "Oups, quelque chose a mal tourné..." (Oops, something went wrong...).

In console logs we have : 

```
TypeError: e.tileMatrixSet.filter is not a function
    at Object.P (289.0af9bccd.js:1:223100)
    at Object.R [as create] (map-library-openlayers-js.d701841c.js:1:182635)
    at Object.a [as createLayer] (289.0af9bccd.js:1:244111)
    at u.createLayer (map-library-openlayers-js.d701841c.js:1:48956)
    at u.value (map-library-openlayers-js.d701841c.js:1:52374)
    at Ol (geOrchestra.js?5f38512cef2803e9bc4a:2:3543098)
    at t.unstable_runWithPriority (geOrchestra.js?5f38512cef2803e9bc4a:2:4527812)
    at zi (geOrchestra.js?5f38512cef2803e9bc4a:2:3488589)
    at Cl (geOrchestra.js?5f38512cef2803e9bc4a:2:3539657)
    at ul (geOrchestra.js?5f38512cef2803e9bc4a:2:3529764)
    at geOrchestra.js?5f38512cef2803e9bc4a:2:3488880
    at t.unstable_runWithPriority (geOrchestra.js?5f38512cef2803e9bc4a:2:4527812)
    at zi (geOrchestra.js?5f38512cef2803e9bc4a:2:3488589)
    at Vi (geOrchestra.js?5f38512cef2803e9bc4a:2:3488825)
    at Wi (geOrchestra.js?5f38512cef2803e9bc4a:2:3488760)
    at il (geOrchestra.js?5f38512cef2803e9bc4a:2:3526263)
```

Can someone reproduce this bug ?

@MaelREBOUX @catmorales @pierrejego @landryb  @tdipisa

**Comment by catmorales** [comment]
we are on an old release of georchestra

**Comment by jusabatier** [comment]
@catmorales 2023.02.00-RC1-geOrchestra is the latest mapstore2-georchestra's release

**Comment by catmorales** [comment]
oh sorry, I get distracted. Yes we plan to deploy 2023.02.00-RC1-geOrchestra when I will back the july 26th. I will on holiday tomorrow.

**Comment by tdipisa** [comment]
@jusabatier we will double check this as part of the RC2 work. Thank you.

**Comment by jusabatier** [comment]
You can access a context with this bug here : https://geoportail.lepuyenvelay.fr/mapstore/#/context/Cadastre

The export function is enabled so you can also get the map.json

**Comment by dsuren1** [comment]
@jusabatier 
The extension are built with old version of MS and it needs to be updated to version equivalent to geOrchestra RC's MS submodule version and has to be rebuilt and imported back to context again. Doing this should solve the issue.

**Comment by jusabatier** [comment]
I confirm it solve the problem.

I simply change the Mapstore2 submodule to [v2023.01.02](https://github.com/geosolutions-it/MapStore2/releases/tag/v2023.01.02) and recompile the extension, and it solve the problem after upgrade mapstore2-cadastrapp extention in Mapstore2 with the generated Zip.

Maybe someone with write acces can update the Mapsore2 submodule to v2023.01.02 and release it ?

**Comment by landryb** [comment]
maybe the submodule should just point at the same commit as the MapStore2 submodule in ms2-georchestra ?

**Comment by dsuren1** [comment]
Yes correct

**Comment by jusabatier** [comment]
If you do so, what commit will you use ? The one from master or from the release ?

I think we should use a release tag commit for releasing a module version.

Also for the versioning of the module, shouldn't it embed the georchestra-mapstore or the mapstore release version ?
This way we know with which version of mapstore it should be used.

**Comment by Gaetanbrl** [comment]
> Also for the versioning of the module, shouldn't it embed the georchestra-mapstore or the mapstore release version ?

MS2 is always embed in a module (depend of developper). So, on start you have to update mapstore2 submodule all the time and build if needed  : 

```
git clone --recursive http://
cd cadastrapp
git submodule update
npm install
npm run build
```

Refs : 

> ref https://github.com/geosolutions-it/MapStoreExtension/issues/57
> ref https://github.com/geosolutions-it/MapStoreExtension/issues/46

---------------
> If you do so, what commit will you use ? The one from master or from the release ?

Normally, for mapstore2-georchestra, we have to use near MapStore2 versions between MapStore2-georchestra and mapstore2 module version.

Refs :

> ref https://github.com/geosolutions-it/MapStoreExtension#compatibility

So i guess this depend if module have to works in latest (so align and fix module with latest MS2 version) or / and works with master (so align and fix module with master ms2 version).

**Comment by landryb** [comment]
fwiw, trying to update the submodule, here's what i did so far:
```
[10/08 15:00] landry@build.fluela:/data/src/georchestra/mapstore2-cadastrapp/MapStore2 $git fetch
[10/08 15:00] landry@build.fluela:/data/src/georchestra/mapstore2-cadastrapp/MapStore2 $git checkout c4f94e3b7b
Updating files: 100% (1656/1656), done.
Previous HEAD position was 223b0f6ee Porting changes from #7881 partially to make standard print option configurable from localConfig/context. (#8205)
HEAD is now at c4f94e3b7 #9314: Fix - Enhance show/hide attribute edit option on Layer (#9317)
[10/08 15:00] landry@build.fluela:/data/src/georchestra/mapstore2-cadastrapp/MapStore2 $cd ..
[10/08 15:00] landry@build.fluela:/data/src/georchestra/mapstore2-cadastrapp $rm -f package-lock.json && npm install && npm run ext:build
```
but so far it utterly fails to build:
```
ERROR in ./node_modules/@cesium/engine/Source/Core/Resource.js 2043:30-44
Module not found: Error: Can't resolve 'zlib' in '/data/src/georchestra/mapstore2-cadastrapp/node_modules/@cesium/engine/Source/Core'
ERROR in ./node_modules/@cesium/engine/Source/Core/Resource.js 2050:39-54
Module not found: Error: Can't resolve 'https' in '/data/src/georchestra/mapstore2-cadastrapp/node_modules/@cesium/engine/Source/Core'
ERROR in ./node_modules/@cesium/engine/Source/Core/Resource.js 2050:57-71
Module not found: Error: Can't resolve 'http' in '/data/src/georchestra/mapstore2-cadastrapp/node_modules/@cesium/engine/Source/Core'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
```
because from what i understand the version of cesium that is in node_modules is 1.90 while the version in MapStore2/node_modules is 1.106.1:
```
$grep _id node_modules/cesium/package.json MapStore2/node_modules/cesium/package.json
node_modules/cesium/package.json:  "_id": "cesium@1.90.0",
MapStore2/node_modules/cesium/package.json:  "_id": "cesium@1.106.1",
```
dunno if that's related to that failure... and if so, should `package.json` be updated ?

i've tried adding 
```
"cesium": "1.106.1"
```
to package.json but that doesnt solve the build failure.  maybe because of npm6/nodejs12 ?

**Comment by jusabatier** [comment]
Here, I did this : 

```
cd mapstore2-cadastrapp
git submodule update --init --recursive
cd MapStore2
git checkout v2023.01.02
cd ..
npm run ext:build => complains about missing mkdirp
npm install --save --legacy-peer-deps mkdirp
npm run ext:build => complains about https protocol
export NODE_OPTIONS=--openssl-legacy-provider
npm run ext:build
```

And I finally success building the addon.

NPM version : 9.8.0
NodeJS version : 18.17.0

**Comment by landryb** [comment]
i have this as a local diff:
```
diff --git a/MapStore2 b/MapStore2
index 223b0f6..c4f94e3 160000
--- a/MapStore2
+++ b/MapStore2
@@ -1 +1 @@
-Subproject commit 223b0f6eec5c5c614a4ad21a318ae35370e3f402
+Subproject commit c4f94e3b7bfd22eaf94e22aebf6d9f1b09a61b6f
diff --git a/webpack.config.js b/webpack.config.js
index 12df863..4026ca2 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -34,6 +34,6 @@ const cfg = buildConfig(
     proxyConfig
 );
 // stream are needed here in code
-cfg.resolve.fallback = {timers: false};
+cfg.resolve.fallback = {timers: false, http: false, https: false, zlib: false}
 cfg.devtool = "eval-source-map";
 module.exports = cfg;
```
but it still fails.

now, with node v18.17.1 & npm v9.6.7:
```
[10/08 16:14] landry@build.fluela:/data/src/georchestra/mapstore2-cadastrapp $npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: CadastrappExtension@1.0.0
npm ERR! Found: eslint@7.8.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.8.1" from the root project
npm ERR!   peer eslint@">= 7.5.0" from @mapstore/eslint-config-mapstore@1.0.3
npm ERR!   node_modules/@mapstore/eslint-config-mapstore
npm ERR!     dev @mapstore/eslint-config-mapstore@"1.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"2.x - 6.x" from eslint-plugin-import@2.20.2
npm ERR! node_modules/eslint-plugin-import
npm ERR!   dev eslint-plugin-import@"2.20.2" from the root project
npm ERR!   peer eslint-plugin-import@">= 2.20.2" from @mapstore/eslint-config-mapstore@1.0.3
npm ERR!   node_modules/@mapstore/eslint-config-mapstore
npm ERR!     dev @mapstore/eslint-config-mapstore@"1.0.3" from the root project
```
that nodejs ecosystem is just a joke.

**Comment by landryb** [comment]
ok, got it finally building with this diff in the MapStore2 submodule:
```
diff --git a/build/createExtensionWebpackConfig.js b/build/createExtensionWebpackConfig.js
index fbab8b223..c83af1fb2 100644
--- a/build/createExtensionWebpackConfig.js
+++ b/build/createExtensionWebpackConfig.js
@@ -35,6 +35,9 @@ module.exports = ({ prod = true, name, exposes, sharedLibrariesEager = true, ali
     resolve: {
         fallback: {
             path: false,
+            http: false,
+            https: false,
+            zlib: false,
             timers: false,
             stream: false
         },
```
@dsuren1 @offtherailz does that make sense to you ? i guess `build/createExtensionWebpackConfig.js` is used when building an external extension like cadastrapp here.. since you added those bits to the other webpack configs in geosolutions-it/MapStore2#9267 ...

with only this diff on top of geosolutions-it/MapStore2@c4f94e3b7bf i've been able to build `dist/Cadastrapp.zip` with node v12.22.12 / npm 6.14.16

**Comment by landryb** [comment]
i can confirm the resulting Cadastrapp.zip build fixes the original issue (broken UF query), running inside 2023.02rc2

**Comment by landryb** [comment]
@dsuren1 @tdipisa to get a working cadastrapp build, should/can i do a PR updating the MS2 submodule like georchestra/mapstore2-georchestra#653 or you plan to do it as part of contract #4 ? we can do the PR/release, just want to make sure where's the limit of what you are contracted for...

afaict the last commit tagged v2.0.0 in https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/v2.0.0 by @MaelREBOUX wont work on 2023.02.

cc @catmorales @jusabatier

**Comment by landryb** [comment]
just made a v2.1.0 release of the extension in https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/v2.1.0 - the `Cadastrapp-v2.1.0.zip` asset was taken from https://github.com/georchestra/mapstore2-cadastrapp/actions/runs/6495176530 but those expire quite fast so this way it's kept available...
