### ISSUE TITLE
Sort by parcel number

### ISSUE THREAD

**Issue by FBeneville** [georchestra/mapstore2-cadastrapp#187]
>Trying to sort by parcel number in a selection doesn't give the expected result
>Looks like it's registred as character instead of number
>Was working in Mapfishapp
![Tri](https://github.com/georchestra/mapstore2-cadastrapp/assets/55783032/c117053a-54df-4c24-804b-317c37c2fd14)

**Comment by FBeneville** [comment]
>Trying to sort by parcel number in a selection doesn't give the expected result
>Looks like it's registred as character instead of number
>Was working in Mapfishapp

**Comment by landryb** [comment]
from my understanding, same bug as reported in #189
