### ISSUE TITLE
Dev Environment Setup

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#2]
The [GeoSolutions DEV environment](https://georchestra.geo-solutions.it/) need to be properly configured in order to start the development:

1. The **QGIS Cadastre Database** and **Cadastrapp DB** databases must be created (more info are available in a [private document](https://docs.google.com/document/d/1dZKJ0Q63dsEkwahvKZeFDs806fIqxiZSJQlwlrGQ8bE/edit?usp=sharing)t for this)
2. The backend part needs also to be installed and configured (the installation guide is available [here](https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/README.md), build instructions [here](https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/README.md#build-application-)). The WAR file is already available [here](http://demo.geo-solutions.it/share/georchestra/cadastrapp-1.10-SNAPSHOT.war)

**Comment by randomorder** [comment]
Ok, my understanding is we want to update the current development environment by:
- creating two extra databases in postgres
- building one extra container (there [seems to be](https://github.com/georchestra/cadastrapp/blob/master/cadastrapp/docker.md) a buildable image available)
- add this container to the docker-compose  on the machine
- configure JNDI connections
- configure the proxy application
- configure the cadastrapp application

**Comment by tdipisa** [comment]
@randomorder I'm not completelly sure that the docker solutions is currently working (look at the comment [here](https://github.com/georchestra/mapstore2-cadastrapp/issues/1#issuecomment-651144962)). Anyway we have the WAR available for the backend part that is of interest for our developments.

**Comment by randomorder** [comment]
let me know if this can be closed @tdipisa

**Comment by tdipisa** [comment]
@randomorder I put it in review since invelved PRs georchestra side are in review too. We are waiting for client's feedback
