### ISSUE TITLE
Owner list results

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#32]
Inside the Owner Search (#16), if the use doesn't select a precise value from the list provided in "Last name and first name" and simply put a partial text matching one or more items in that list, it is however possible to click on search button to open the **Owner result list**, where a list of owners matching the partial text speficied by the user is provided in a floating panel.

![image.png](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/08ac5e21-5719-4b90-85cc-10f9387d04b2)

- The user can select one or more owners in the list to see their plots in the usual Plot Selection table (#12): a floating panel can be used in the MS plugin for the **Owner result list**

- The user can download in PDF or CSV format the **Properties details** of connected plots in the same way it is possible inside the Information Form (#13): for the MS plugin the same component can be used in both cases

- The user can export the list of owners in CSV: the Ms plugin can simply replicate that export functionality with a dedicate button in the floating panel

![owner_list_cadastrapp.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/4cf44fe5-e784-4887-a7e7-01b116527a11)

- Same happens for co-owners search. If the text of property is not complete, instead of opening a new plot, allows to browse owners first (this time from `coowner` service).

**Comment by offtherailz** [comment]
co-owner has the same behavior (I added a line in issue description for this @tdipisa ).
