### ISSUE TITLE
Display tools and data based on role

### ISSUE THREAD

**Issue by offtherailz** [georchestra/mapstore2-cadastrapp#36]
The Tools and data shown should respect the functionality matrix [available online](http://docs.georchestra.org/cadastrapp/guide_developpeur/index.html#). Access to them is defined by the CNIL level.
### Restriction to verify
Here an extraction (to double check) of the functionalities limited by user level. 

####  CNIL1 and CNIL2 only
- [x] Popup info --> some data is reserved. (proprietaires and some data about unité fonciere)
- [x] PlotSelection --> export (menu with 4 options - Plot - Owners - CoOwners - Bundle ). Otherwise a simple button that allows only plot export
- [x] Rechercher des propriétaires (all)
- [x] Fenêtre de sélection de parcelles:
    - [x] Exporter liste de propriétaires (CSV) 
    - [x] Exporter liste de co-propriétaires (CSV)
    - [x] Exporter lots de co-propriétés (PDF)
    - [x] Exporter lots de co-propriétés (CSV)
- [x] Fiche information parcelle
    - [x] Plots Info form -> Owners radio button for PDF download
    - [x] onglet Propriétaires 
    - [x] onglet Copropriétaires
- [x] Traitement des sélections
   - [x] Export liste CSV
- [ ] Unité foncière
   - [ ] Infos sur le(s) propriétaire(s)
- [x] Module de demande d’information foncière (all)
- [x] Request form. 
    - [x] Options Owners, co-owners and "Lot co-owners" for request object are reserved. 
    - [x] "Generate documents" is reserved.

#### CNL2 only
- [x] Fiche information parcelle 
    - [x] onglet Bâtiments 
    - [x] onglet Subdivisions fiscales ( "Relevé de propriété PDF", "Relevé de propriété CSV" and "Lots en PDF" signed with a ? for CNIL1)

**Comment by tdipisa** [comment]
Few points below after a first test:

1. Search for plot for example in Rue De Brest 6 (Cadastral address) select the record and click on land unit button. 

**Result in Mapfishapp**

![2021_02_08_13_15_22_Information_sur_une_unité_foncière](https://user-images.githubusercontent.com/1280027/107218360-d1180c80-6a0f-11eb-8339-a7aa9c377384.png)

Result in MS: the part in RED above is missing even if I'm authenticated with the same admin user. The result below should be the one for user without permissions to see owner data.

![image](https://user-images.githubusercontent.com/1280027/107218246-a8901280-6a0f-11eb-8b2b-4e5093fb2e33.png)

@offtherailz what about **Module de demande d’information foncière (all)**? Where I can test it?
