### ISSUE TITLE
Cadastrapp 2nd round of test issues - Information Form

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#43]
Tests mainly related to the Information Form:

- [x] Owners "Check all" checks in Plot search and not in Info Form->Owners tab. the same for Co-Owners

![infoform_1.gif](https://images.zenhubusercontent.com/5c9ca89d6607b6793c66ec35/44a0c908-ab2d-43e3-b011-11daa29315c6)

- [x] The default Owner export function, generates an PDF with the result reported twice (for both "only this plots" and "All Properties")

- [x] The CSV export function in Owners tab fails with an error 500

- [x] The Info form button in Plot Search is always enabled even if no records are selected in the search table

**Comment by offtherailz** [comment]
I was able to replicate and fix 1st and last point. 
- 2nd point give me the same results of the original application. 
Can you provide more details about how to replicate the 3rd point? is works form me. (tested with 350238000AD0230, first record of owners table)
- 3rd point. I'm able to export the csv (zip) file correctly.

**Comment by tdipisa** [comment]
@offtherailz 
To replicate the issue you have to select more than one Owner
![image](https://user-images.githubusercontent.com/1280027/106164602-74546080-618a-11eb-9935-b053455ee4b2.png)
