### ISSUE TITLE
leftover debug message in console

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#69]
enabling cadastrapp extension/button, console gets 91 log messages printed, all coming from the same line of cadastrapp code:
```
Object { "$$typeof": Symbol(react.element), type: t(), key: null, ref: null, props: {…}, _owner: null }
138.9e2867c6.js:1:336047
Object { "$$typeof": Symbol(react.element), type: t(), key: null, ref: null, props: {…}, _owner: null }
138.9e2867c6.js:1:336047
...
```

**Comment by landryb** [comment]
panning on the map produces more log lines in the console, always the same.

**Comment by landryb** [comment]
can confirm this is fixed, thanks !

**Comment by landryb** [comment]
fixed by #79

**Comment by MaelREBOUX** [comment]
not fixed here : I have the same lines.

**Comment by landryb** [comment]
maybe check what version you're running ?

**Comment by MaelREBOUX** [comment]
no idea how to find this info. @catmorales ?

**Comment by catmorales** [comment]
>maybe check what version you're running ?

docker image tagged 1.2.x installed  deployed last monday

**Comment by tdipisa** [comment]
@offtherailz can you please further check this in 1.2.x?

**Comment by offtherailz** [comment]
This is an issue of cadastrapp. Cadastrapp doesn't have a formal version that you can identify in UI or files.
It have to be installed using the zip file, and you can get the latest from the github action.

**Comment by offtherailz** [comment]
I did an rc for testing. https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc2
You can download the zip from that github release, with all the fixes that are now in test column (also default style changes PR I merged some minutes ago)

**Comment by offtherailz** [comment]
JFI I added pre-release zip rc3 with the fixes of today
https://github.com/georchestra/mapstore2-cadastrapp/releases/tag/1.0.0-rc3
