### ISSUE TITLE
Cadastre Tools - General UI panel and basic configuration

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#7]
The basic component for the cadastrapp tool need to be provided to contains the whole set of functionalities (the mockup [here](http://demo.geo-solutions.it/mockups/mapstore2/cadastrapp/#/config)). Part of this issue is also the initial definition of the plugin configuration also for backend services (the functionalities matrix [here](http://docs.georchestra.org/cadastrapp/guide_developpeur/index.html#)).

![image](https://user-images.githubusercontent.com/1280027/95200058-0ac8d480-07de-11eb-926a-5455174d84f4.png)

**Comment by offtherailz** [comment]
#21 was an initial porting of the mockup, as a real extension for GeOrchestra
#23 Add the support for inital configuration loading
#24 Finalizes the structure of the toolbar and provides a baseline for unit tests.
