### ISSUE TITLE
option to display cadastrapp pane by default

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#72]
As of now, to get the cadastrapp pane users need two clicks: burger menu -> cadastrapp.

is there a way to display/expand the pane by default when the plugin is loaded in a context ? afaict it's not possible in the current state of the plugin.

cc @catmorales @MaelREBOUX

**Comment by offtherailz** [comment]
There was already an option to open it on startup in the old application?

**Comment by landryb** [comment]
there was no option but the toolbar was visible by default

**Comment by offtherailz** [comment]
I found it, the option is `openToolbarOnLoad` in `manifest.json` is false on your installation, but debugging I've seen that in the code is true.
Probably there is another way to configure the old app that I ignore. 
In our installation I have to click on the button to show the cadatrapp toolbar, but I've seen in your instance the cadastrapp toolbar shows on startup. 
In our case is not a toolbar, so I'll call it `openOnLoad`, and I'll make it configurable by `cfg`

**Comment by landryb** [comment]
right, `openToolbarOnLoad` is true in our config for the previous mfapp cadastrapp client. Having it configurable this way would work for me, thanks !

**Comment by offtherailz** [comment]
I added `openOnLoad' cfg option to the plugin. If true, the panel will auto-open on startup.
See the [readme](https://github.com/georchestra/mapstore2-cadastrapp#plugin-configuration) for all oconfig options and how to set.
