### ISSUE TITLE
prevent conflicts between cadastrapp pane & identify tool panes

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#73]
right now, the cadastrapp pane is above anything else - eg if enabled, it hides the omnibar plugin & identify tool results pane. The tools in the lower right are still displayed though.

What if a user wants to search for an address in the omnibar field while still using cadastrapp tools ? he needs to close cadastrapp pane, recenter on his address, then reopen the cadastrapp pane (gladly, now it keeps its own state so selection tabs/searches arent lost).

What if the identify tool is still enabled, and the user clicks on the map to query another layer ? the identify tool results pane will be displayed *below* the cadastrapp pane, and is thus hidden.

UI-wise, would there be a way to switch from one of the panes to the other ? an accordion ? tabs in the pane ?
Should we still display the omnibar when the cadastrapp pane is open, at the risk of cluttering the little space left to the map ?

cc @catmorales @MaelREBOUX

**Comment by MaelREBOUX** [comment]
Hum... Good questions.

For me the pb is not to heavy for the identify tool as we have the persistent user session. We can close cadastrapp, activate the identify tool, reading infos then reactivate cadastrapp. iti working.

But we have a problem with the main search panel ! Because we always want to search and zoom to an adresse for example.
In this case, I proposed tha the search panel have to float on the left, as the vertical tools panel.

Need discussions...

**Comment by tdipisa** [comment]
@MaelREBOUX @landryb 

>right now, the cadastrapp pane is above anything else - eg if enabled, it hides the omnibar plugin & identify tool results pane. The tools in the lower right are still displayed though.
>What if a user wants to search for an address in the omnibar field while still using cadastrapp tools ? he needs to close cadastrapp pane, recenter on his address, then reopen the cadastrapp pane (gladly, now it keeps its own state so selection tabs/searches arent lost).

This is the design we presented so far and, as we agreed during our meetings, for this reason we made sure to keep the state of the cadastrapp tool when it is closed. 

>What if the identify tool is still enabled, and the user clicks on the map to query another layer ? the identify tool results pane will be displayed below the cadastrapp pane, and is thus hidden.

The Identify panel should be visualized anyway: we will check this.

>UI-wise, would there be a way to switch from one of the panes to the other ? an accordion ? tabs in the pane ?
Should we still display the omnibar when the cadastrapp pane is open, at the risk of cluttering the little space left to the map ?

I'm sorry, it is not really clear to me. Can you please clarify?

**Comment by landryb** [comment]
> > UI-wise, would there be a way to switch from one of the panes to the other ? an accordion ? tabs in the pane ?
> > Should we still display the omnibar when the cadastrapp pane is open, at the risk of cluttering the little space left to the map ?
> 
> I'm sorry, it is not really clear to me. Can you please clarify?

what i mean is that instead of having to continuously close/open cadastrapp pane to get the omnibar, or see the result of an object identification, if there was a way to have the panes 'coexist' on the display. We dont want floating windows for sure, but tabs in the pane title was an idea, or an accordion like you used to display several parcel information in the same popover.

**Comment by MaelREBOUX** [comment]
>>    What if the identify tool is still enabled, and the user clicks on the map to query another layer ? the identify tool results pane will be displayed below the cadastrapp pane, and is thus hidden.

> The Identify panel should be visualized anyway: we will check this.

Thanks for that.

**Comment by offtherailz** [comment]
The simpler solutions is to display identify result above cadastrapp, reducing the z-index of cadastrapp. I'm going to commit this solution, so you can try if it fits your needings.
![identify](https://user-images.githubusercontent.com/1279510/109654798-e8579f00-7b62-11eb-8dc7-97da3c07471d.gif)

**Comment by landryb** [comment]
thanks, that seems fine for this usecase!

as for the omnibar, its a bit sad to have close/open the cadastrapp pane..
