### ISSUE TITLE
use nodata translated string where appropriate

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#77]
in the parcel info window for various tabs, if there's no data to display in the table, "No Data" is written, probably coming from https://github.com/georchestra/mapstore2-cadastrapp/blob/8cca780b079868143b55532ca865cffdbe8599ef/js/extension/components/information/HistoryMutation.jsx#L7  https://github.com/georchestra/mapstore2-cadastrapp/blob/8cca780b079868143b55532ca865cffdbe8599ef/js/extension/components/information/building/Description.jsx#L114 https://github.com/georchestra/mapstore2-cadastrapp/blob/8cca780b079868143b55532ca865cffdbe8599ef/js/extension/components/information/building/Description.jsx#L161 and https://github.com/georchestra/mapstore2-cadastrapp/blob/8cca780b079868143b55532ca865cffdbe8599ef/js/extension/components/table/EmptyRowsView.jsx#L7

i think those should use the "nodata" string from the translations, either `cadastrapp.infobulle.nodata` from https://github.com/georchestra/mapstore2-cadastrapp/blob/8cca780b079868143b55532ca865cffdbe8599ef/assets/translations/data.fr-FR.json#L25 or `cadastrapp.popup.nodata` from https://github.com/georchestra/mapstore2-cadastrapp/blob/8cca780b079868143b55532ca865cffdbe8599ef/js/extension/components/popup/__tests__/PopupViewer-test.js#L51 (is this one even valid ?)

**Comment by offtherailz** [comment]
I moved the no-data string in `cadastrapp.nodata`, so it is a common string that can be used globally. 
I also added "loading" to localization, as I noticed it was on the same row and fixed the wrong line in test.

**Comment by landryb** [comment]
thanks, PR #80 looks good !

**Comment by MaelREBOUX** [comment]
Sounds goot to me too.
