### ISSUE TITLE
searching for a parcel sometimes creates 2 or 3 selection tabs

### ISSUE THREAD

**Issue by landryb** [georchestra/mapstore2-cadastrapp#81]
i havent been able to figure out what happens, but sometimes when i search a parcel by ref and click *once* on 'search' button, 2 or 3 selection tabs are opened (with the same result/content) instead of a single one.

**Comment by MaelREBOUX** [comment]
I can reproduce.
In the current cadastrapp, each search is providing results in the same tab. It is a better behaviour.

Possible @offtherailz  ?

**Comment by MaelREBOUX** [comment]
Sorry for the confusion @landryb  I created #97 

Cannot reproduce your behaviour yet here (in FF).

**Comment by offtherailz** [comment]
I can not reproduce it too, @landryb. 
Did you find this problem again?
Could you find a set of reproducible steps or suggest some hints to reproduce this issue?

**Comment by landryb** [comment]
dunno.. it wasnt happening all the time. maybe blame it on the mouse ? will report here if it happens again..

**Comment by tdipisa** [comment]
ok, I'm going to close for the moment.
