### ISSUE TITLE
One ticket for listing strings enhancement

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#86]
Please all report here your suggestions to enhance strings in the UI.

I'll push a specific PR from our fork.

**Comment by MaelREBOUX** [comment]
I start with "Bâtiments" in the plot information : miss the ^

![image](https://user-images.githubusercontent.com/6370443/108975481-d53a6000-7686-11eb-902c-c0c62c69806e.png)

**Comment by MaelREBOUX** [comment]
On plot information, parcel tab, then BP export :

![image](https://user-images.githubusercontent.com/6370443/108981841-6dd3de80-768d-11eb-8440-704b9fceeeb6.png)

"Exportation" is not suitable but I don't fnd this string in the localization files.

**Comment by MaelREBOUX** [comment]
Well : I propose to put all this strings in the singular form

![image](https://user-images.githubusercontent.com/6370443/108983919-a8d71180-768f-11eb-97f4-ec6bc310f759.png)

**Comment by landryb** [comment]
> On plot information, parcel tab, then BP export :
> 
> ![image](https://user-images.githubusercontent.com/6370443/108981841-6dd3de80-768d-11eb-8440-704b9fceeeb6.png)
> 
> "Exportation" is not suitable but I don't fnd this string in the localization files.

i've already fixed this one for "Exporter", cf #78

**Comment by MaelREBOUX** [comment]
![image](https://user-images.githubusercontent.com/6370443/109000803-7552b200-76a4-11eb-90cb-0035ccf8be8b.png)

I propose a new string : just "code"
because it take too much height

**Comment by MaelREBOUX** [comment]
`"counter": "au guichet",` should be better with `"desk": "au guichet",`

**Comment by landryb** [comment]
> `"counter": "au guichet",` should be better with `"desk": "au guichet",`

not a big deal since its only a key ?

**Comment by MaelREBOUX** [comment]
Seen this in the Request form :

![image](https://user-images.githubusercontent.com/6370443/109306420-723ff900-783f-11eb-8ed7-a0d72b403a06.png)

No idea where to localize that.

**Comment by tdipisa** [comment]
@MaelREBOUX do we still need this issue open?

**Comment by MaelREBOUX** [comment]
Yes. I just open #116 as specific issue.
