### ISSUE TITLE
BP exportation : the choice of the background is not taken

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#89]
When I ask a B&W background for the bordereau parcellaire I always get the colour version.

**Comment by tdipisa** [comment]
@MaelREBOUX can you please speficy more details in description please (eg. some steps to reproduce)? then I will ask developers for a check.

**Comment by MaelREBOUX** [comment]
linked to #88 maybe ?

I asked for a B&W background in the BP and I always get the coloured background in the PDF.

**Comment by tdipisa** [comment]
@MaelREBOUX Can we close this? Did you try this using the latest version of the cadastrapp tool?

**Comment by MaelREBOUX** [comment]
need to test next week. sorry to be late.

**Comment by MaelREBOUX** [comment]
Sorry : still misworking with ther last build https://github.com/georchestra/mapstore2-cadastrapp/suites/2379569218/artifacts/50518522

**Comment by MaelREBOUX** [comment]
I close because the worry is now in #88
