### ISSUE TITLE
Action Toolbar - Point Selection

### ISSUE THREAD

**Issue by tdipisa** [georchestra/mapstore2-cadastrapp#9]
This tool allows the possibility to select a cadastral parcel simply by clicking on map. 

![image](https://user-images.githubusercontent.com/1280027/95204222-11f2e100-07e4-11eb-9343-ef05df4cee3a.png)

The search tool to activate in this case MS side is the following one (according to the mockup [here](http://demo.geo-solutions.it/mockups/mapstore2/cadastrapp/#/config)).

![2020_10_06_14_59_22_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/95205217-5d59bf00-07e5-11eb-8dc7-89c303da6047.png)

As soon as the user activates the **Point selection** (toggle button), it is possible to click on map. Each click on map generates the corresponding search request to the cadastrapp backend to populate the results table in **Plots selection**:

- At the first click on map the **Plots selection** panel opens to show results in the results table: a first table Tab is automatically created to hosts the result
- With each subsequent click on map **results are visualized in the active Tab**: if the user adds a new table search Tab before clicking on map, results are reported there
- As soon as the backend response is received, the record is added in table and the cadastral parcel highlighted on map along with the previous selected ones
- All records in a table search Tab are highlighted in map until the user closes the Tab itself, create a new empty Tab or switches to another search Tab with some results available: in that last case the selection in map changes accordingly by showing the cadastral parcels corresponding to the selected Tab.
- As soon as at least a result is available in a table search Tab, the Zoom button is enabled in **Plots search** to allow zooming the map to the whole set of records available in that search Tab or just to the selected records, if any.

![2020_10_06_14_54_58_MapStore_HomePage](https://user-images.githubusercontent.com/1280027/95204142-fab3f380-07e3-11eb-9bb9-64a294382c74.png)

![cadastrap_point](https://user-images.githubusercontent.com/1280027/95206169-a5c5ac80-07e6-11eb-8350-be06bf3cedab.gif)

**Comment by offtherailz** [comment]
Note for testers: zoom to has one issue with centering the panel yet. See #30 for this
