### ISSUE TITLE
plot information : copro tab : lack localization on button "Properties list"

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#90]
![image](https://user-images.githubusercontent.com/6370443/109002031-f65e7900-76a5-11eb-8171-26566fdc224b.png)

Should be "Relevé de propriété" (ie releve.depropriete ?) like on the Owner tab

**Comment by tdipisa** [comment]
@MaelREBOUX As far as I understood during our last meeting, you will send a PR to update/review FR translations. Should we wait for this PR?

**Comment by MaelREBOUX** [comment]
I have open a specific branch to push all the modifications.

But I can't find this specific string.
I fear our cadastrapp is not align to master....

**Comment by tdipisa** [comment]
@MaelREBOUX you are referring to the Info Form therefore it should be [this one](https://github.com/georchestra/mapstore2-cadastrapp/blob/master/assets/translations/data.fr-FR.json#L66). Anyway we can take care of this, don't worry.
