### ISSUE TITLE
UI : cannot load another layers whil cadastrapp is open

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#94]
The main "burger" menu is hidden by cadastrapp

So one cannot add a new layer in the map while working without closing cadastrapp and so losing all.

![image](https://user-images.githubusercontent.com/6370443/109029080-c5407180-76c2-11eb-85d7-57b2ff1fb8ef.png)

What are opinion of @catmorales ? @landryb ? @jusabatier  ?

**Comment by landryb** [comment]
duplicate of #73 ?

**Comment by MaelREBOUX** [comment]
Heu : no as the lower vertical toolbar which has the identify too is now moving to the left.
I think...

**Comment by landryb** [comment]
yes, but #73 is precisely about this, you can use the identify tool, but you cant see the results as they're behind the cadastrapp pane.

**Comment by MaelREBOUX** [comment]
This is another thing for me.
but +1 I also see the pb the identify tool masked.

But re-testing this morning, as we have the session user stored : we lost anything.
So I close.
