### ISSUE TITLE
searching for a parcel by reference / adresses / owner... creates a new tab at every search

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#97]
Sorry for confusion with #81 @landryb 

In mapstore, each search creates a new selection tab.
In the current mapfishapp cadastrapp, each search is providing results in the same tab. It is a better behaviour.

Possible @offtherailz ?

**Comment by tdipisa** [comment]
@MaelREBOUX 

>In mapstore, each search creates a new selection tab.
In the current mapfishapp cadastrapp, each search is providing results in the same tab. It is a better behaviour.

I'm sorry but it isn't correct, it depends by what kind of search you are performing: there are different combinations.
For example in the old plugin, if you perform searches through a spatial selection on map, results are displayed in the same tab and the same is in MapStore. If you manually open a new tab and activate it then new spatial selections are displayed in the new tab (this is the same in MS).
If you perform a search by Owner, for example, results are always displayed in a new dedicate tab. This is what happens in mapfishapp and also in MS.

At least that's how it works in the geosolutions instance, and it seems to me in portail-test as well.

Please, compare all same search types between mapfishapp and the MS cadastrapp tool and let us know if you find specific discrepancies.

**Comment by MaelREBOUX** [comment]
You are right @tdipisa
