### ISSUE TITLE
Change default colors selection settings

### ISSUE THREAD

**Issue by MaelREBOUX** [georchestra/mapstore2-cadastrapp#98]
![image](https://user-images.githubusercontent.com/6370443/109147680-90392b00-7765-11eb-9eae-9afb309b6719.png)

![image](https://user-images.githubusercontent.com/6370443/109147709-9b8c5680-7765-11eb-8577-af3f299d6c4f.png)

**Comment by MaelREBOUX** [comment]
For the list :
* fill color = #F78B97
* stroke color = FF0000
* stroke width : 2 px

For the selection :
* fill color = #00FF18
* stroke color = 0112FF
* stroke width : 2 px

**Comment by tdipisa** [comment]
@MaelREBOUX as far as I can see in your context here, default style values are overridden by the ones you put in configuration

**Comment by landryb** [comment]
i dont mind of you want to change the default colors, just make that '**early**' so that ppl doing screenshots for documentations dont have to redo their screenshots :)

**Comment by MaelREBOUX** [comment]
Surely done by @catmorales

But as I want to change it at source : where is it ?
because I also have to put our GeoServer wokspace in the cadastrapp repo so I want the colors to be "aligned".

I found this but I thoink it is not that ?
https://github.com/georchestra/mapstore2-cadastrapp/blob/master/localConfig.json#L291-L306

**Comment by landryb** [comment]
my guess would be the defaults are in https://github.com/georchestra/mapstore2-cadastrapp/blob/master/js/extension/constants.js#L30, applied here: https://github.com/georchestra/mapstore2-cadastrapp/blob/master/js/extension/components/modals/Preferences.jsx#L22

**Comment by MaelREBOUX** [comment]
Thank you @landryb  PR done

to link to this very very old issue https://github.com/georchestra/cadastrapp/issues/297

**Comment by catmorales** [comment]
@MaelREBOUX I can change it on the application context which is used for testing.
later, we fear the configuration in the default file.

**Comment by offtherailz** [comment]
I accepted the PR, before seing the last comment of @catmorales ?
Is it ok anyway to change the defaults that way?

**Comment by catmorales** [comment]
OK for me . Thank you @offtherailz
